# 端口
server:
  port: 7102
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: shipping-management
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # redis token信息
  redis:
    key:
      prefix:
        userToken: "user:token:"
        passwordError: "user:password:error:"
        permissionRefresh: "user:token:permissionRefresh:"
      expire:
        userToken: 604800 # 7天 7*24*3600
        passwordError: 3600 # 一个小时
        permissionRefresh: 604800 # 7天 7*24*3600
    allowMultipleLogin: true # 允许多处登陆

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/${project.database}/**/*.xml,classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: deleted

#使用代码生成模块时 指定要生成的表存在于哪种数据库，可选值有【mysql、oracle、sqlServer】
project:
  database: mysql

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:
              6000

